version: "3.9"

services:
  app:
    image: my-app:latest
    build:
      context: .
      dockerfile: Dockerfile
    container_name: app
    environment:
      - CONTAINER_TIMEOUT=10
      - DOCKER_HOST=unix:///var/run/docker.sock
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock # Allow access to Docker daemon
    networks:
      - app-network
    ports:
      - "8080:8080" # Expose the WebSocket server for the slaves to connect

  hash_extractor:
    image: servuc/hash_extractor:latest
    deploy:
      replicas: 1
      restart_policy:
        condition: any
    command: ["/hash_extractor", "s", "ws://app:3000"]
    networks:
      - app-network
    depends_on:
      - app

networks:
  app-network:
    driver: bridge
