version: "3.9"

services:
  app:
    image: your-application-image:latest
    build:
      context: .
      dockerfile: Dockerfile
    container_name: app
    environment:
      - CONTAINER_TIMEOUT=10
      - DOCKER_HOST=unix:///var/run/docker.sock
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock # For accessing Docker daemon
    networks:
      - app-network
    ports:
      - "3000:3000" # Expose the WebSocket server for the slaves to connect

  hash_extractor:
    image: servuc/hash_extractor:latest
    deploy:
      replicas: 1
      restart_policy:
        condition: any
    command: ["s", "ws://app:3000"] # Connect to the WebSocket server in the app
    networks:
      - app-network
    depends_on:
      - app

networks:
  app-network:
    driver: bridge
