version: "3.9"

services:
  app:
    image: theleaddestroyer:latest
    build:
      context: .
      dockerfile: Dockerfile
    container_name: app
    environment:
      - MIN_REPLICAS=1
      - MAX_REPLICAS=5
      - THRESHOLD=3
      - DOCKER_HOST=unix:///var/run/docker.sock
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock  # Needed for Docker SDK access
    networks:
      - app-network
    ports:
      - "8080:8080"

networks:
  app-network:
    driver: bridge
